#!/usr/bin/env bash

red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
blue=$(tput setaf 4)
normal=$(tput sgr0)
bold=$(tput bold)

mysqlHost=""
mysqlPort="3306"
mysqlDb="pufferpanel"
mysqlUser="root"
mysqlPass=""

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

function printSeparator() {
    echo "------------"
}

function loadConfig() {
    if [ "${mysqlHost}" == "" ]; then
        configPath=${DIR}/config.json
        mysqlHost=$(php -r 'echo json_decode(file_get_contents("'${configPath}'"))->mysql->host;');
        mysqlDb=$(php -r 'echo json_decode(file_get_contents("'${configPath}'"))->mysql->database;');
        mysqlUser=$(php -r 'echo json_decode(file_get_contents("'${configPath}'"))->mysql->username;');
        mysqlPass=$(php -r 'echo json_decode(file_get_contents("'${configPath}'"))->mysql->password;');
        mysqlPort=$(php -r 'echo json_decode(file_get_contents("'${configPath}'"))->mysql->port;');
    fi
}

function configureMysql() {

    mysqlHost="localhost"
    type mysql 1>/dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo "MySQL isn't able to install. Error: MySQL was not found within your PATH."
        exit 1;
    fi

    echo "Welcome to the Ecliptic Panel Intaller, thanks for choosing us!."
    echo ""
    echo -n "First we must get some information. Do you want to continue (y/n)?"
    read continue
    if [ "${continue}" = "y" ]; then
        echo "Great! Before we get started we must ask a couple of simple questions."
        echo "These questions will help setup the database!"
        printSeparator
        echo "MySQL Configuration"
        echo -n "Enter MySQL Hostname [localhost]: "
        read temp
        if [ "${temp}" != "" ]; then
            mysqlHost=${temp}
        fi
        echo -n "Enter MySQL Username (MUST HAVE GRANT PRIVLAGES) [root]: "
        read temp
        if [ "${temp}" != "" ]; then
            mysqlPort=${temp}
        fi
        notValid=true
        while ${notValid}; do
        echo -n "Enter the MySQL account password: "
        read -s temp
        if [ "${temp}" != "" ]; then
            mysqlPass=${temp}
        fi
        if mysql -h ${mysqlHost} -P ${mysqlPort} -u ${mysqlUser} --password="${mysqlPass}" -e "exit"; then
            notValid=false
        else
            echo "ERROR: Database connection cound not be established."
        fi
        done
    else
    echo "Okay then, installation was cancelled!"
    fi

    echo ""
    echo "Creating EclipticPanel account now....."
    mysql -h ${mysqlHost} -P ${mysqlPort} -u ${mysqlUser} --password="${mysqlPass}" < install/install.sql
    mysql -h ${mysqlHost} -P ${mysqlPort} -u ${mysqlUser} --password="${mysqlPass}" -e "SET GLOBAL event_scheduler = ON;"

    newUser="eclipticpanel"
    newPw=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9,.:\-@[]-_\-#+*~&%' | fold -w 32 | head -n 1)
    newHost=$(mysql -h ${mysqlHost} -P ${mysqlPort} -D ${mysqlDb} -u ${mysqlUser} --password="${mysqlPass}" -sN -e "SELECT USER()")
	newHost=${newHost/${mysqlUser}@}

    mysql -h ${mysqlHost} -P ${mysqlPort} -D ${mysqlDb} -u ${mysqlUser} --password="${mysqlPass}" -e "
     GRANT ALL PRIVILEGES ON eclipticpanel.* TO 'eclipticpanel'@'${newHost}' IDENTIFIED BY '${newPw}';
     GRANT ALL PRIVILEGES ON eclipticpanel.* TO 'eclipticpanel'@'localhost' IDENTIFIED BY '${newPw}';
    "
    echo "{
    \"mysql\": {
        \"host\": \"${mysqlHost}\",
        \"database\": \"${mysqlDb}\",
        \"username\": \"${newUser}\",
        \"password\": \"${newPw}\",
        \"port\": \"${mysqlPort}\"
    }
}" > config.json
    echo "Success! The database was successfully created and is now active!"
    echo "Switching to new user for further commands"
    mysqlHost=""
    loadConfig
}